// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace botForTRPO.Models;

public partial class KerfusContext : DbContext
{
    public KerfusContext()
    {
    }

    public KerfusContext(DbContextOptions<KerfusContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CatchedSignal> CatchedSignals { get; set; }

    public virtual DbSet<ChannelsForNotification> ChannelsForNotifications { get; set; }

    public virtual DbSet<Satellite> Satellites { get; set; }

    public virtual DbSet<Signal> Signals { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
    {
        optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=Kerfus;Integrated Security=True;Encrypt=False");
        optionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
    }
    

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CatchedSignal>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__CatchedS__3214EC2762381D11");

            entity.ToTable("CatchedSignal");

            entity.Property(e => e.AudioPath).IsRequired();
            entity.Property(e => e.SignalID).HasMaxLength(12);

            entity.HasOne(d => d.Signal).WithMany(p => p.CatchedSignals)
                .HasForeignKey(d => d.SignalID)
                .HasConstraintName("FK__CatchedSi__Signa__68487DD7");
        });

        modelBuilder.Entity<ChannelsForNotification>(entity =>
        {
            entity.HasKey(e => e.GuildID).HasName("PK__Channels__3A3F890F8DA44FCD");

            entity.Property(e => e.GuildID).ValueGeneratedNever();
        });

        modelBuilder.Entity<Satellite>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Satellit__3214EC2755EE918E");

            entity.ToTable("Satellite");

            entity.HasIndex(e => e.CodeName, "UQ__Satellit__404488D582CCF9AE").IsUnique();

            entity.Property(e => e.CodeName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Hashcode).HasMaxLength(10);
            entity.Property(e => e.Repairs).HasDefaultValueSql("((0))");
        });

        modelBuilder.Entity<Signal>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Signal__3214EC27FCF4AB4B");

            entity.ToTable("Signal");

            entity.Property(e => e.ID).HasMaxLength(12);
            entity.Property(e => e.Duration_Sec).HasDefaultValueSql("((5))");
            entity.Property(e => e.LevelForEvent).HasDefaultValueSql("((3))");
            entity.Property(e => e.Rarity).HasDefaultValueSql("((1))");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}