// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace botForTRPO.Models;

public partial class Satellite
{
    public long ID { get; set; }

    public string CodeName { get; set; }

    public string Hashcode { get; set; }

    public long? Repairs { get; set; }

    public bool IsBreak { get; set; }
}