// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace botForTRPO.Models;

public partial class Signal
{
    public string ID { get; set; }

    public byte Rarity { get; set; }

    public bool Special { get; set; }

    public bool Disposable_Day { get; set; }

    public byte? LevelForEvent { get; set; }

    public int Duration_Sec { get; set; }

    public virtual ICollection<CatchedSignal> CatchedSignals { get; set; } = new List<CatchedSignal>();
}